version: '3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    volumes: 
      - ./db:/var/lib/mysql
    ports: 
      - ${MYSQL_PORT}:3306
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
